routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

//Add Controller
Route::resource('user','UserController');
//Route::resource('permission','PermissionController');
Route::resource('role','RoleController');
Route::resource('products','ProductsController');
Route::resource('systemFlags','SystemFlagsController');
Route::resource('select2Search','Select2SearchController');
Route::resource('person','PersonController');
Route::resource('invoice','InvoiceController');
Route::resource('priceList','PriceListController');
Route::resource('accounts','AccountsController');

Route::get('/accountHead', 'AccountsController@accountHead')->middleware(['auth'])->name('accounts.accountHead');
Route::get('/PriceList', 'PriceListController@PriceList')->middleware(['auth'])->name('priceList.PriceList');
Route::get('/priceList/productRateUpdate/{id}/{price}', 'PriceListController@ProductRateUpdate')->middleware(['auth']);
Route::get('/salesInvoice', 'InvoiceController@salesInvoice')->middleware(['auth'])->name('invoice.salesInvoice');
Route::get('/SIASO', 'InvoiceController@SIASO')->middleware(['auth'])->name('invoice.SIASO');
Route::get('/salesOrder', 'InvoiceController@salesOrder')->middleware(['auth'])->name('invoice.salesOrder');
Route::get('/printSalesInvoice/{id}', 'InvoiceController@printSalesInvoice')->middleware(['auth'])->name('invoice.printSalesInvoice');

Route::get('/purchaseInvoice', 'InvoiceController@purchaseInvoice')->middleware(['auth'])->name('invoice.purchaseInvoice');
Route::get('/purchaseOrder', 'InvoiceController@purchaseOrder')->middleware(['auth'])->name('invoice.purchaseOrder');
Route::get('/PIAPO', 'InvoiceController@PIAPO')->middleware(['auth'])->name('invoice.PIAPO');

Route::get('/customers', 'PersonController@customers')->middleware(['auth'])->name('person.customers');
Route::get('/supplier', 'PersonController@supplier')->middleware(['auth'])->name('person.supplier');

Route::get('/products', 'ProductsController@products')->middleware(['auth'])->name('products.products');
Route::post('/storeProducts', 'ProductsController@storeProducts')->middleware(['auth'])->name('products.storeProducts');

Route::get('/unit', 'SystemFlagsController@unit')->middleware(['auth'])->name('systemFlags.unit');
Route::post('/storeUnit', 'SystemFlagsController@storeUnit')->middleware(['auth'])->name('systemFlags.storeUnit');

Route::get('/category', 'SystemFlagsController@category')->middleware(['auth'])->name('systemFlags.category');
Route::post('/storeCategory', 'SystemFlagsController@storeCategory')->middleware(['auth'])->name('systemFlags.storeCategory');

Route::get('/search', 'Select2SearchController@search')->middleware(['auth'])->name('select2Search.index');
Route::get('/ajax-autocomplete-search', 'Select2SearchController@selectSearch')->middleware(['auth'])->name('select2Search.selectSearch');

Route::get('/profile', 'UserController@profile')->middleware(['auth'])->name('user.profile');


Route::post('/profile', 'UserController@postProfile')->middleware(['auth'])->name('user.postProfile');
Route::post('/addprofile', 'UserController@addProfile')->middleware(['auth'])->name('user.addProfile');
Route::get('/registration', 'UserController@userRegistration')->middleware(['auth'])->name('user.userRegistration');


Route::post('/assignRoleToUser', 'RoleController@assignRoleToUser')->middleware(['auth'])->name('role.assignRoleToUser');
Route::get('/assignroles', 'RoleController@assignroles')->middleware(['auth'])->name('role.assignroles');
Route::post('/addassignroles', 'RoleController@addassignroles')->middleware(['auth'])->name('role.addassignroles');
Route::get('/assignpermission', 'RoleController@assignpermission')->middleware(['auth'])->name('role.assignpermission');
Route::post('/addpermission', 'RoleController@addpermission')->middleware(['auth'])->name('role.addpermission');
Route::get('/createpermission', 'RoleController@createpermission')->middleware(['auth'])->name('role.createpermission');
Route::post('/assignpermissiontorole', 'RoleController@assignpermissiontorole')->middleware(['auth'])->name('role.assignpermissiontorole');
Route::get('/unassignpermissiontorole/{roleid}/{permissionid}', 'RoleController@unassignpermissiontorole')->middleware(['auth'])->name('role.unassignpermissiontorole');

// Route::post('/password/change', 'UserController@postPassword')->middleware(['auth'])->name('userPostPassword');



require __DIR__.'/auth.php';

resources/views/dashboard.blade.php
@extends('master')

@section('title')
  Dashboard
@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol style="display:none;" class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v3</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- /.col-md-6 -->
          <div class="col-lg-6">
            <div class="card">
              <div class="card-header border-0">
                <div class="d-flex justify-content-between">
                  <h3 class="card-title">Sales</h3>
                  <a href="javascript:void(0);">View Report</a>
                </div>
              </div>
              <div class="card-body">
                <div class="d-flex">
                  <p class="d-flex flex-column">
                    <span class="text-bold text-lg">$18,230.00</span>
                    <span>Sales Over Time</span>
                  </p>
                  <p class="ml-auto d-flex flex-column text-right">
                    <span class="text-success">
                      <i class="fas fa-arrow-up"></i> 33.1%
                    </span>
                    <span class="text-muted">Since last month</span>
                  </p>
                </div>
                <!-- /.d-flex -->

                <div class="position-relative mb-4">
                  <canvas id="sales-chart" height="200"></canvas>
                </div>

                <div class="d-flex flex-row justify-content-end">
                  <span class="mr-2">
                    <i class="fas fa-square text-primary"></i> This year
                  </span>

                  <span>
                    <i class="fas fa-square text-gray"></i> Last year
                  </span>
                </div>
              </div>
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  @endsection()

resources/views/master.blade.php
<!--Header with Side Menu & Navbar -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>@yield('title') - Expeditious</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{asset('../../plugins/fontawesome-free/css/all.min.css')}}">
  <!-- IonIcons -->
  <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.7.0/css/buttons.dataTables.min.css">
  
  <link href="{{asset('plugins/select2/css/select2.min.css')}}" rel="stylesheet" />
  
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('../../dist/css/adminlte.min.css')}}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <!-- Data Table -->
  <link rel="stylesheet" href="{{asset('plugins/datatables-bs4/css/dataTables.bootstrap4.css')}}">
  <!-- Custome Marquee Effects -->
  <style>
    .marquee {
      margin: 0 auto;
      width: 100%;
      height: 30px;
      white-space: nowrap;
      overflow: hidden;
      box-sizing: border-box;
      position: relative;
      
      &:before, &:after {
        position: absolute;
        top: 0;
        width: 50px;
        height: 30px;
        content: "";
        z-index: 1;
      }
      &:before {
        left: 0;
        background: linear-gradient(to right, white 5%, transparent 100%);
      }
      &:after {
        right: 0;
        background: linear-gradient(to left, white 5%, transparent 100%);
      }
    }

    .marquee__content {
      width: 300% !important;
      display: flex;
      line-height: 30px;
      animation: marquee 40s linear infinite forwards;
      &:hover {
        animation-play-state: paused;
      } 
    }

    .list-inline {
      display: flex;
      justify-content: space-around;
      width: 33.33%;
      
      /* reset list */
      list-style: none;
      padding: 0;
      margin: 0;
    }
    @keyframes marquee {
      0% { transform: translateX(75%); }
      100% { transform: translateX(-66%); }
    }
  </style>
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to to the body tag
to get the desired effect
|---------------------------------------------------------|
|LAYOUT OPTIONS | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition sidebar-mini layout-footer-fixed">
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>      
    </ul>

    <div class="marquee">
      <div class="marquee__content">
        <ul class="list-inline">
          <li>Expeditious - Simple Solutions for Complex Problem</li>          
        </ul>
      
      </div>
    </div>
        <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">     
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="fas fa-user-cog"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">          
          <a href="/profile" class="dropdown-item">
          <i class="fas fa-user-edit"></i> Edit Profile
          </a>
          <div class="dropdown-divider"></div>
          <form method="POST" action="{{ route('logout') }}">                                                  
            @csrf
            <a href="route('logout')" class="dropdown-item"   
              onclick="event.preventDefault();this.closest('form').submit();">
              <i class="fas fa-sign-out-alt"></i> logout            
            </a>
          </form>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#"><i
            class="fas fa-th-large"></i></a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
      <img src="dist/img/AdminLTELogo.png" alt="Expetitious Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Expetitious</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">      
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->          
               <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-warehouse"></i>
              <p>
                Inventry
                <i class="fas fa-angle-left right"></i>                
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ route('systemFlags.unit')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Add Product Unit</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('systemFlags.category', ['systemFlag'=>'CATEGORY'])}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Add Product Category</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('products.products')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Add Product</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('priceList.PriceList')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Price List</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-file-invoice-dollar"></i>
              <p>
                Invoice & Orders
                <i class="fas fa-angle-left right"></i>                
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ route('invoice.salesInvoice')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Sales Invoice</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('invoice.salesOrder')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Sales Order</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('invoice.purchaseOrder')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Purchase Order</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('invoice.purchaseInvoice')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Purchase Invoice</p>
                </a>
              </li>
              
            </ul>
          </li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-address-book"></i>
              <p>
                Accounts
                <i class="fas fa-angle-left right"></i>                
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ route('person.customers')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Customers</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('person.supplier')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Suppliers</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('accounts.accountHead')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Account Head</p>
                </a>
              </li>
              
            </ul>
          </li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-pen-square"></i>
              <p>
                Master Entry
                <i class="fas fa-angle-left right"></i>                
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="/registration" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Add App User</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('role.index')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Role</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('role.createpermission')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Permissions</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('role.assignroles')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Assign Role</p>
                </a>
              </li>
            </ul>
          </li>                       
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

<!--- Body data will be appere-->
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    @include('partials.alert')
    @yield('content')
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer" align="center">
    <strong>Copyright &copy; 2021-2022 Expeditious It Solution.</strong>
    All rights reserved.    
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{{asset('plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap -->
<script src="{{asset('plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE -->
<script src="{{asset('dist/js/adminlte.js')}}"></script>
<script src="{{asset('dist/js/adminlte.min.js')}}"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="{{asset('plugins/chart.js/Chart.min.js')}}"></script>
<script src="{{asset('dist/js/demo.js')}}"></script>
<script src="{{asset('dist/js/pages/dashboard3.js')}}"></script>
<!-- Data Table -->
<script src="{{asset('plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
<script src="https://cdn.datatables.net/buttons/1.7.0/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.7.0/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.7.0/js/buttons.colVis.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.5.2/bootbox.min.js"></script>


@yield('scripts')
</body>
</html>