routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

//Add Controller
Route::resource('user','UserController');
//Route::resource('permission','PermissionController');
Route::resource('role','RoleController');
Route::resource('products','ProductsController');
Route::resource('systemFlags','SystemFlagsController');
Route::resource('select2Search','Select2SearchController');
Route::resource('person','PersonController');
Route::resource('invoice','InvoiceController');
Route::resource('priceList','PriceListController');
Route::resource('accounts','AccountsController');

Route::get('/accountHead', 'AccountsController@accountHead')->middleware(['auth'])->name('accounts.accountHead');
Route::get('/PriceList', 'PriceListController@PriceList')->middleware(['auth'])->name('priceList.PriceList');
Route::get('/priceList/productRateUpdate/{id}/{price}', 'PriceListController@ProductRateUpdate')->middleware(['auth']);
Route::get('/salesInvoice', 'InvoiceController@salesInvoice')->middleware(['auth'])->name('invoice.salesInvoice');
Route::get('/SIASO', 'InvoiceController@SIASO')->middleware(['auth'])->name('invoice.SIASO');
Route::get('/salesOrder', 'InvoiceController@salesOrder')->middleware(['auth'])->name('invoice.salesOrder');
Route::get('/printSalesInvoice/{id}', 'InvoiceController@printSalesInvoice')->middleware(['auth'])->name('invoice.printSalesInvoice');

Route::get('/purchaseInvoice', 'InvoiceController@purchaseInvoice')->middleware(['auth'])->name('invoice.purchaseInvoice');
Route::get('/purchaseOrder', 'InvoiceController@purchaseOrder')->middleware(['auth'])->name('invoice.purchaseOrder');
Route::get('/PIAPO', 'InvoiceController@PIAPO')->middleware(['auth'])->name('invoice.PIAPO');

Route::get('/customers', 'PersonController@customers')->middleware(['auth'])->name('person.customers');
Route::get('/supplier', 'PersonController@supplier')->middleware(['auth'])->name('person.supplier');

Route::get('/products', 'ProductsController@products')->middleware(['auth'])->name('products.products');
Route::post('/storeProducts', 'ProductsController@storeProducts')->middleware(['auth'])->name('products.storeProducts');

Route::get('/unit', 'SystemFlagsController@unit')->middleware(['auth'])->name('systemFlags.unit');
Route::post('/storeUnit', 'SystemFlagsController@storeUnit')->middleware(['auth'])->name('systemFlags.storeUnit');

Route::get('/category', 'SystemFlagsController@category')->middleware(['auth'])->name('systemFlags.category');
Route::post('/storeCategory', 'SystemFlagsController@storeCategory')->middleware(['auth'])->name('systemFlags.storeCategory');

Route::get('/search', 'Select2SearchController@search')->middleware(['auth'])->name('select2Search.index');
Route::get('/ajax-autocomplete-search', 'Select2SearchController@selectSearch')->middleware(['auth'])->name('select2Search.selectSearch');

Route::get('/profile', 'UserController@profile')->middleware(['auth'])->name('user.profile');


Route::post('/profile', 'UserController@postProfile')->middleware(['auth'])->name('user.postProfile');
Route::post('/addprofile', 'UserController@addProfile')->middleware(['auth'])->name('user.addProfile');
Route::get('/registration', 'UserController@userRegistration')->middleware(['auth'])->name('user.userRegistration');


Route::post('/assignRoleToUser', 'RoleController@assignRoleToUser')->middleware(['auth'])->name('role.assignRoleToUser');
Route::get('/assignroles', 'RoleController@assignroles')->middleware(['auth'])->name('role.assignroles');
Route::post('/addassignroles', 'RoleController@addassignroles')->middleware(['auth'])->name('role.addassignroles');
Route::get('/assignpermission', 'RoleController@assignpermission')->middleware(['auth'])->name('role.assignpermission');
Route::post('/addpermission', 'RoleController@addpermission')->middleware(['auth'])->name('role.addpermission');
Route::get('/createpermission', 'RoleController@createpermission')->middleware(['auth'])->name('role.createpermission');
Route::post('/assignpermissiontorole', 'RoleController@assignpermissiontorole')->middleware(['auth'])->name('role.assignpermissiontorole');
Route::get('/unassignpermissiontorole/{roleid}/{permissionid}', 'RoleController@unassignpermissiontorole')->middleware(['auth'])->name('role.unassignpermissiontorole');

// Route::post('/password/change', 'UserController@postPassword')->middleware(['auth'])->name('userPostPassword');



require __DIR__.'/auth.php';

app/Models/SystemFlags.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SystemFlags extends Model
{
    use HasFactory;

    protected $primaryKey = 'id';
    protected $fillable = ['flagName','flagType','modifiedBy','createdBy','parentId'];

   public static function getSystemFlagName($id){

        $systemFlag =  SystemFlags::find($id);
        return $systemFlag->flagName??'';
   }
}

app/Http/Controllers/SystemFlagsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\SystemFlags;

class SystemFlagsController extends Controller
{
    //

    public function __construct(SystemFlags $systemFlags)
    {
        $this->middleware("auth");
        $this->systemFlags = $systemFlags;
    }
    public function show($id)
    {
        $Data = systemFlags::find($id);

        if($Data->flagType == 'UNIT' ){
            SystemFlags::where('id', $id)->delete();
            $systemFlags = systemFlags::where('flagType','UNIT')->get();
            return redirect()->route('systemFlags.unit')->with('success',$Data->flagName.' Unit deleted');
        }
        else if($Data->flagType == 'CATEGORY' ){
            SystemFlags::where('id', $id)->delete();
            $systemFlags = systemFlags::where('flagType','CATEGORY')->get();
            return redirect()->route('systemFlags.category', ['systemFlag'=>'CATEGORY'])->with('success',$Data->flagName.' Category deleted');
        }
        else{
            return Redirect::back()->with(['error', 'Kindly contact with support person.']);
        }
    }    
    

    public function storeUnit(Request $request)
    {
        $request->validate([
            'flagName' => 'required|string',
            'flagType' => 'required|string'
        ]);

        if(!empty($request->id)){
            $systemFlags = systemFlags::find($request->id);
            $systemFlags->flagName = $request["flagName"];
            $systemFlags->updated_at = date("Y-m-d h:i:s");
            $systemFlags->modifiedBy = auth()->user()->name;
            if($systemFlags->save()){
                return redirect()->route('systemFlags.unit')->with('success', $request["flagName"].' Unit Updated');
            }else{
                return redirect()->route('systemFlags.unit')->with('error', 'Error Occured');
            }

        }else{
            $systemFlags = $this->systemFlags->create([
                'flagName' => $request->flagName,
                'createdBy' => auth()->user()->name,
                'modifiedBy' => auth()->user()->name,
                'flagType' => $request->flagType
            ]);
    
            return redirect()->route('systemFlags.unit')->with('success', $request["flagName"].' Unit Created');
        }
        
        
    }
    
    public function storeCategory(Request $request)
    {
        $request->validate([
            'flagName' => 'required|string',
            'flagType' => 'required|string'
        ]);

        
        if(!empty($request->id)){
            $systemFlags = systemFlags::find($request->id);
            $systemFlags->flagName = $request["flagName"];
            $systemFlags->updated_at = date("Y-m-d h:i:s");
            $systemFlags->parentId = $request["parentId"];
            $systemFlags->modifiedBy = auth()->user()->name;
            if($systemFlags->save()){
                return redirect()->route('systemFlags.category', ['systemFlag'=>'CATEGORY'])->with('success', $request["flagName"].' Category Updated');
            }else{
                return redirect()->route('systemFlags.category', ['systemFlag'=>'CATEGORY'])->with('error', 'Error Occured');
            }

        }else{
            $systemFlags = $this->systemFlags->create([
                'flagName' => $request->flagName,
                'parentId'=>$request->parentId,
                'createdBy' => auth()->user()->name,
                'modifiedBy' => auth()->user()->name,
                'flagType' => $request->flagType
            ]);
    
            return redirect()->route('systemFlags.category', ['systemFlag'=>'CATEGORY'])->with('success', $request["flagName"].' Category Created');
        }
        
        
    }

    // public function getAll(){
    //     $systemFlags = $this->systemFlags->all();
    //     return response()->json([
    //         'systemFlags' => $systemFlags
    //     ], 200);
    // }

    public function edit($id)
    {
        $Data = systemFlags::find($id);

        if($Data->flagType == 'UNIT' ){
            $systemFlags = systemFlags::where('flagType','UNIT')->get();
            return view('systemFlags.unit', ['units' => $systemFlags,'UnitData'=> $Data]);
        }
        else if($Data->flagType == 'CATEGORY' ){
            $systemFlags = systemFlags::where('flagType','CATEGORY')->get();
            //return view('systemFlags.category', ['categorys' => $systemFlags,'categoryData'=> $Data]);
            return redirect()->route('systemFlags.category', ['systemFlag'=>'CATEGORY','isEdit'=>'1','id'=>$id]);
        }
        else{
            return Redirect::back()->with(['error', 'Kindly contact with support person.']);
        }
        
            //->with('roleData', $roleData);
    }

    public function unit()
    {
        $systemFlags =systemFlags::where('flagType','UNIT')->get();
        return view('systemFlags.unit', ['units' => $systemFlags]);
    }

    public function category()
    {
        
        $systemFlags =systemFlags::where('flagType','CATEGORY')->get();
        if(isset($_GET['isEdit'])){
            $Data = systemFlags::find($_REQUEST['id']);
            return view('systemFlags.category', ['categorys' => $systemFlags,'categoryData'=> $Data]);
        }else{
            return view('systemFlags.category', ['categorys' => $systemFlags]);
        }
        
    }

    public function destroy($id)
    {
        //it goes to show method
    }

}

resources/views/systemFlags/category.blade.php
<?php

use App\Models\SystemFlags;


  $systemFlag = $_GET['systemFlag'];
  $parentCategory = SystemFlags::where('flagType','CATEGORY')->get();
?>
@extends('master')

@section('title')
Category
@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Categorys</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol style="display:none;" class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v3</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- /.col-md-6 -->
          <div class="col-lg-12">
            <div class="card">  
            @if(isset($categoryData) )
            <form method="POST" action="{{ route('systemFlags.storeCategory') }}">
                @csrf
                <div class="card-body">
                      <div class="form-group">
                        <label for="name">Category Id</label>
                        <input type="text" name="id"  id="id" class="form-control @error('id') is-invalid @enderror" value="{{ $categoryData->id }}" readonly>
                        @error('id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    
                    <div class="form-group">
                        <input type="hidden" name="flagType" style="width:25%"  id="flagType" 
                        class="form-control @error('flagType') is-invalid @enderror" value="<?php echo $systemFlag;?>" readonly>
                    </div>
                    <div class="form-group">
                        <label for="name">Category Name</label>
                        <input type="text" name="flagName"  style="width:25%"  id="flagName" class="form-control @error('flagName') is-invalid @enderror" 
                                value="{{ $categoryData->flagName }}" required placeholder="Category Name" autocomplete="off">
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="parentId">Parent Category</label>
                        <select type="text" name="parentId"  style="width:25%"  id="parentId" class="form-control @error('parentId') is-invalid @enderror" 
                                placeholder="Parent Category" autocomplete="off">
                                <option value='0'>Select Category</option>
                            @foreach ($parentCategory as $Category)
                                @if($Category->id == $categoryData->parentId)
                                <option selected value='{{$Category->id}}'>{{ $Category->flagName }}</option>                                    
                                @else
                                    <option value='{{$Category->id}}'>{{ $Category->flagName }}</option>
                                @endif                                
                            @endforeach
                        </select>
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Update Category</button>
                </div>
              </form>
            @else
            <form method="POST" action="{{ route('systemFlags.storeCategory') }}">
                @csrf
                <div class="card-body">
                      <div class="form-group">
                        <label for="id">Category Id</label>
                        <input type="text" name="id" style="width:25%"  id="id" class="form-control @error('id') is-invalid @enderror" value="{{ old('id') }}" readonly>
                        @error('id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <input type="hidden" name="flagType" style="width:25%"  id="flagType" 
                        class="form-control @error('flagType') is-invalid @enderror" value="<?php echo $systemFlag;?>" readonly>
                    </div>
                      
                    <div class="form-group">
                        <label for="name">Category Name</label>
                        <input type="text" name="flagName"  style="width:25%"  id="flagName" class="form-control @error('name') is-invalid @enderror" 
                              value="{{ old('name') }}" required placeholder="Category Name" autocomplete="off">
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="name">Parent Category</label>
                        <select type="text" name="parentId"  style="width:25%"  id="parentId" class="form-control @error('parentId') is-invalid @enderror" 
                                placeholder="Parent Category" autocomplete="off">
                                <option value='0'>Select Category</option>
                            @foreach ($parentCategory as $Category)
                                <option value='{{$Category->id}}'>{{ $Category->flagName }}</option>                                    
                            @endforeach
                        </select>
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="card-footer">
                @if(userHasPermission('Add Product Category'))
                    <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Create Category</button>
                @endif
                  </div>
              </form>
            @endif
              
            </div>
            <div class="card">                              
              <div class="card-body table-responsive p-0">
                  <table id="CategorysDataTable" class="table table-hover table-bordered table-striped">
                      <thead>
                          <tr>
                              <th>ID</th>
                              <th>Category</th>
                              <th>Date Posted</th>
                              <th>Action</th>
                          </tr>
                      </thead>
                      <tbody>
                          @forelse ($categorys as $Category)
                              <tr>
                                  <td>{{ $Category->id }}</td>
                                  <td>{{ $Category->flagName }}</td>
                                  <td>{{ $Category->created_at }}</td>
                                  <td>
                                  @if(userHasPermission('Edit Product Category'))
                                      <a href="{{ route('systemFlags.edit', $Category->id) }}" class="btn btn-sm btn-warning">Edit Category</a>
                                  @endif
                                  @if(userHasPermission('Delete Product Category'))
                                      <a href="{{ route('systemFlags.destroy', $Category->id) }}" class="btn btn-sm btn-danger">Delete Category</a>
                                  @endif 
                                    </td>
                              </tr>
                          @empty
                              <tr>No Result Found</tr>
                          @endforelse
                      </tbody>
                  </table>
              </div>
            <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  @endsection()

@section('scripts')
<script>
  $(function () {
    $('#CategorysDataTable').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });

  $( document ).ready(function() {
    $('#parentId').select2();
    // $('#parentId').select2({
    //     placeholder: 'Select Parenter',
    //     ajax: {
    //         url: '/ajax-autocomplete-search',
    //         data: function (params) {
    //         var query = {
    //             search: params.term,
    //             type: 'public',
    //             table: 'system_flags',
    //             column1:"id",
    //             column2:"flagName",
    //             where: "flagType='CATEGORY'"
    //         }
    //         return query;},
    //         dataType: 'json',
    //         delay: 250,
    //         processResults: function (data) {
    //             return {
    //                 results: $.map(data, function (item) {
    //                     return {
    //                         text: item.flagName,
    //                         id: item.id
    //                     }
    //                 })
    //             };
    //         },
    //         cache: true
    //     }
    // });
});
  

</script>

@endsection()

resources/views/systemFlags/unit.blade.php
@extends('master')

@section('title')
Unit
@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Units</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol style="display:none;" class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v3</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- /.col-md-6 -->
          <div class="col-lg-12">
            <div class="card">  
            @if(isset($UnitData) )
            <form method="POST" action="{{ route('systemFlags.storeUnit') }}">
                @csrf
                <div class="card-body">
                      <div class="form-group">
                        <label for="name">Unit Id</label>
                        <input type="text" name="id"  id="id" class="form-control @error('id') is-invalid @enderror" value="{{ $UnitData->id }}" readonly>
                        @error('id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    
                    <div class="form-group">
                        <input type="hidden" name="flagType" style="width:25%"  id="flagType" class="form-control @error('flagType') is-invalid @enderror" value="UNIT" readonly>
                    </div>
                    <div class="form-group">
                        <label for="name">Unit Name</label>
                        <input type="text" name="flagName"  style="width:25%"  id="flagName" class="form-control @error('flagName') is-invalid @enderror" 
                                value="{{ $UnitData->flagName }}" required placeholder="Unit Name" autocomplete="off">
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Update Units</button>
                </div>
              </form>
            @else
            <form method="POST" action="{{ route('systemFlags.storeUnit') }}">
                @csrf
                <div class="card-body">
                      <div class="form-group">
                        <label for="id">Unit Id</label>
                        <input type="text" name="id" style="width:25%"  id="id" class="form-control @error('id') is-invalid @enderror" value="{{ old('id') }}" readonly>
                        @error('id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <input type="hidden" name="flagType" style="width:25%"  id="flagType" class="form-control @error('flagType') is-invalid @enderror" value="UNIT" readonly>
                    </div>
                      
                    <div class="form-group">
                        <label for="name">Unit Name</label>
                        <input type="text" name="flagName"  style="width:25%"  id="flagName" class="form-control @error('name') is-invalid @enderror" 
                              value="{{ old('name') }}" required placeholder="Unit Name" autocomplete="off">
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="card-footer">
                @if(userHasPermission('Add Product Units'))
                    <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Create Units</button>
                @endif
                  </div>
              </form>
            @endif
              
            </div>
            <div class="card">                              
              <div class="card-body table-responsive p-0">
                  <table id="unitsDataTable" class="table table-hover table-bordered table-striped">
                      <thead>
                          <tr>
                              <th>ID</th>
                              <th>Unit</th>
                              <th>Date Posted</th>
                              <th>Action</th>
                          </tr>
                      </thead>
                      <tbody>
                          @forelse ($units as $unit)
                              <tr>
                                  <td>{{ $unit->id }}</td>
                                  <td>{{ $unit->flagName }}</td>
                                  <td>{{ $unit->created_at }}</td>
                                  <td>
                                  @if(userHasPermission('Edit Product Units'))
                                      <a href="{{ route('systemFlags.edit', $unit->id) }}" class="btn btn-sm btn-warning">Edit unit</a>
                                  @endif   
                                  @if(userHasPermission('Delete Product Units'))
                                      <a href="{{ route('systemFlags.destroy', $unit->id) }}" class="btn btn-sm btn-danger">Delete unit</a>
                                  @endif 
                                    </td>
                              </tr>
                          @empty
                              <tr>No Result Found</tr>
                          @endforelse
                      </tbody>
                  </table>
              </div>
            <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  @endsection()

@section('scripts')
<script>
  $(function () {
    $('#unitsDataTable').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
@endsection()