routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

//Add Controller
Route::resource('user','UserController');
//Route::resource('permission','PermissionController');
Route::resource('role','RoleController');
Route::resource('products','ProductsController');
Route::resource('systemFlags','SystemFlagsController');
Route::resource('select2Search','Select2SearchController');
Route::resource('person','PersonController');
Route::resource('invoice','InvoiceController');
Route::resource('priceList','PriceListController');
Route::resource('accounts','AccountsController');

Route::get('/accountHead', 'AccountsController@accountHead')->middleware(['auth'])->name('accounts.accountHead');
Route::get('/PriceList', 'PriceListController@PriceList')->middleware(['auth'])->name('priceList.PriceList');
Route::get('/priceList/productRateUpdate/{id}/{price}', 'PriceListController@ProductRateUpdate')->middleware(['auth']);
Route::get('/salesInvoice', 'InvoiceController@salesInvoice')->middleware(['auth'])->name('invoice.salesInvoice');
Route::get('/SIASO', 'InvoiceController@SIASO')->middleware(['auth'])->name('invoice.SIASO');
Route::get('/salesOrder', 'InvoiceController@salesOrder')->middleware(['auth'])->name('invoice.salesOrder');
Route::get('/printSalesInvoice/{id}', 'InvoiceController@printSalesInvoice')->middleware(['auth'])->name('invoice.printSalesInvoice');

Route::get('/purchaseInvoice', 'InvoiceController@purchaseInvoice')->middleware(['auth'])->name('invoice.purchaseInvoice');
Route::get('/purchaseOrder', 'InvoiceController@purchaseOrder')->middleware(['auth'])->name('invoice.purchaseOrder');
Route::get('/PIAPO', 'InvoiceController@PIAPO')->middleware(['auth'])->name('invoice.PIAPO');

Route::get('/customers', 'PersonController@customers')->middleware(['auth'])->name('person.customers');
Route::get('/supplier', 'PersonController@supplier')->middleware(['auth'])->name('person.supplier');

Route::get('/products', 'ProductsController@products')->middleware(['auth'])->name('products.products');
Route::post('/storeProducts', 'ProductsController@storeProducts')->middleware(['auth'])->name('products.storeProducts');

Route::get('/unit', 'SystemFlagsController@unit')->middleware(['auth'])->name('systemFlags.unit');
Route::post('/storeUnit', 'SystemFlagsController@storeUnit')->middleware(['auth'])->name('systemFlags.storeUnit');

Route::get('/category', 'SystemFlagsController@category')->middleware(['auth'])->name('systemFlags.category');
Route::post('/storeCategory', 'SystemFlagsController@storeCategory')->middleware(['auth'])->name('systemFlags.storeCategory');

Route::get('/search', 'Select2SearchController@search')->middleware(['auth'])->name('select2Search.index');
Route::get('/ajax-autocomplete-search', 'Select2SearchController@selectSearch')->middleware(['auth'])->name('select2Search.selectSearch');

Route::get('/profile', 'UserController@profile')->middleware(['auth'])->name('user.profile');


Route::post('/profile', 'UserController@postProfile')->middleware(['auth'])->name('user.postProfile');
Route::post('/addprofile', 'UserController@addProfile')->middleware(['auth'])->name('user.addProfile');
Route::get('/registration', 'UserController@userRegistration')->middleware(['auth'])->name('user.userRegistration');


Route::post('/assignRoleToUser', 'RoleController@assignRoleToUser')->middleware(['auth'])->name('role.assignRoleToUser');
Route::get('/assignroles', 'RoleController@assignroles')->middleware(['auth'])->name('role.assignroles');
Route::post('/addassignroles', 'RoleController@addassignroles')->middleware(['auth'])->name('role.addassignroles');
Route::get('/assignpermission', 'RoleController@assignpermission')->middleware(['auth'])->name('role.assignpermission');
Route::post('/addpermission', 'RoleController@addpermission')->middleware(['auth'])->name('role.addpermission');
Route::get('/createpermission', 'RoleController@createpermission')->middleware(['auth'])->name('role.createpermission');
Route::post('/assignpermissiontorole', 'RoleController@assignpermissiontorole')->middleware(['auth'])->name('role.assignpermissiontorole');
Route::get('/unassignpermissiontorole/{roleid}/{permissionid}', 'RoleController@unassignpermissiontorole')->middleware(['auth'])->name('role.unassignpermissiontorole');

// Route::post('/password/change', 'UserController@postPassword')->middleware(['auth'])->name('userPostPassword');



require __DIR__.'/auth.php';

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;
use Auth;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\Models\User;
use App\Models\roleHasPermissionHistory;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(Role $role)
    {
        $this->middleware("auth");
        $this->role = $role;
    }
    public function index()
    {
        $roles= $this->role::all();
        return view('role.index', ['roles' => $roles]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('role.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string'
            
        ]);

        if(!empty($request->id)){
            $role = role::find($request->id);
            $role->name = $request["name"];
            $role->updated_at = date("Y-m-d h:i:s");
            if($role->save()){
                return redirect()->route('role.index')->with('success', 'Role Created');
            }else{
                return redirect()->route('role.index')->with('error', 'Error Occured');
            }

        }else{
            $role = $this->role->create([
                'name' => $request->name
            ]);
    
            return redirect()->route('role.index')->with('success', 'Role Created');
        }
        
        
    }

    public function getAll(){
        $roles = $this->role->all();
        return response()->json([
            'roles' => $roles
        ], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $roles = $this->role->all();

        $roleData = role::find($id);

        return view('role.index', ['roles' => $roles,'roleData'=> $roleData]);
            //->with('roleData', $roleData);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // echo $_GET;
        // var_dump($_GET);
        // $role = role::find($id);
        // $role->name = $request["name"];
        // var_dump($request);
        // if($role->save()){
        //     return redirect()->route('role.index')->with('success', 'Role Created');
        // }else{
        //     return redirect()->route('role.index')->with('error', 'Error Occured');
        // }
            echo "12345";
        
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    

    public function assignroles(){
        $users = User::all();       
        $role = Role::all();
        return view('role.assignrole',['users'=>$users, 'roles'=>$role]);
    } 
    
    public function assignRoleToUser(Request $request){
        
        if(isset($_POST['userid']) && $_POST['userid'] != ''){            
            $user = User::find($request->userid);
            if (count($user->roles->all()) > 0){
                $user->removeRole($user->roles->first());
            }            
            $user->assignRole($request->rolename);

            return redirect()->route('role.assignroles')->with('success', 'Invoice created successfully');    
       }        
        $users = User::all(); 
        
        $role = Role::all();
        return view('role.assignrole',['users'=>$users, 'roles'=>$role])>with('success', 'Role Assigned');    
    }

   public function assignpermission(Request $request){
       $role = Role::where('id', $request->id)->first();
       $permission = Permission::all();
    return view('role.assignpermission',['roles'=>$role, 'permissions'=>$permission]);    
   }   

   public function createpermission(){
       return view('role.createpermission');    
   }

   public function addpermission(Request $request){
     
        $permission = new Permission;
        $permission->name = $request->permission;
        $permission->save();

        return redirect()->route('role.createpermission')->with('success', 'Permission Created');
       
    }

    public function assignpermissiontorole(Request $request) {
        $name = Auth::user()->name;
        $permissionid = Permission::where('name', $request->permission)->first('id');

            $role = Role::find($request->roleid);
                      
            $role->givePermissionTo($request->permission);

           $permissionhistory = new roleHasPermissionHistory();
           $permissionhistory->permission_id = $permissionid->id;
           $permissionhistory->role_id = $request->roleid;
           $permissionhistory->createdBy = $name;
           $permissionhistory->save();

          return redirect()->route('role.assignpermission', ['id'=>$request->roleid])->with('success', 'Permission Assign To Role');

    }

    public function unassignpermissiontorole($roleid, $permissionid) {

        $role = Role::find($roleid);
        $role->revokePermissionTo($role->permissions->where('id', $permissionid));

        return 'Permission Unssign From Role';

    }

    


}

resources/views/role/assignpermission.blade.php
<?php 
use App\Models\SystemFlags;
use App\Models\Products;
use App\Models\Person;
use App\Models\PriceList;
use App\Models\User;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\Models\roleHasPermission;
?>
@extends('master')

@section('title')
Permission Roles
@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Permission Roles</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol style="display:none;" class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v3</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- /.col-md-6 -->
          <div class="col-lg-12">
              <div class="card">
                 <div class="card-body">
                 <form method="POST" action="{{route('role.assignpermissiontorole')}}">  
                    @csrf
                    <div class="col-md-4">
                    <input type="hidden" class="form-control" id="roleid" name="roleid" value="{{$roles->id}}" readonly />                    
                     <div class="mb-3">
                       <label class="form-label">Role</label> <br>
                       <input type="text" class="form-control" id="role" name="role" value="{{$roles->name}}" readonly />                    
                      </div>       
                        <label>
                                <b>   Permission   </b>
                        </label>
                        <br>
                       <div class="product-show">
                               <select class="form-control" name="permission" >
                                 @foreach($permissions as $permission)
                                <option value="{{$permission->name}}">{{$permission->name}}</option>
                                 @endforeach 
                               </select>
                       </div> <br>
                      <div class="mb-3">
                           <input type="submit" class="btn btn-primary" value="Assign Permission" />
                      </div>  
                </div>
                </form>
              </div>  
            </div>
            </div>  
        </div>
        <!-- /.row -->

        <div class="card">                              
              <div class="card-body table-responsive p-0">
                  <table id="productsDataTable" class="table table-hover table-bordered table-striped">
                      <thead>
                          <tr>
                              <th>Name</th>
                              <th>Role</th>
                              <th>Action</th>
                          </tr>
                      </thead>
                      <tbody>
                          @forelse (roleHasPermission::all() as $permission)
                            @if($roles->id == $permission->RoleName->id )
                              <tr>
                                  <td>{{ $permission->PermissionName->name }}</td>
                                  <td>{{ $permission->RoleName->name }}</td>
                                  <td>
                                  <input type="button" value="Remove" class="btn btn-sm btn-danger" onclick="unassignpermissionfromrole({{ $permission->RoleName->id }}, {{$permission->PermissionName->id }});">
                                </td>
                              </tr>
                             @endif 
                          @empty
                              <tr>No Result Found</tr>
                          @endforelse
                      </tbody>
                  </table>
              </div>
            <!-- /.card-body -->
            </div>
            <!-- /.card -->
       
        <!-- /.card-body -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  @endsection()

@section('scripts')

<script>

function unassignpermissionfromrole(roleid, permissionid){
     
    bootbox.confirm("Want to unasign permission form role", function(result) {
      $.ajax({        
        url: "/unassignpermissiontorole/" + roleid + "/" + permissionid
      })
      .done(function( data ) {
        bootbox.alert(data);
        });
        location.reload();
      });
  }

 

  $(function () {
    // $('#invoice_date').val(new Date().toDateInputValue());
    $('#invoiceDataTable').DataTable({
      "initComplete": function () {
            // Apply the search
            this.api().columns().every( function () {
                var that = this;
 
                $( 'input', this.footer() ).on( 'keyup change clear', function () {
                    if ( that.search() !== this.value ) {
                        that
                            .search( this.value )
                            .draw();
                    }
                } );
            } );
        },
      "dom": 'Bfrtip',
      "buttons": [
            'copyHtml5',
            'excelHtml5',
            'csvHtml5',
            'pdfHtml5',
            'colvis'
        ],
      "paging": true,
      "lengthChange": false,
      "searching": true,
      "ordering": true,
      "info": true,
    });
  });

</script>
@endsection()

resources/views/role/assignrole.blade.php
<?php 
use App\Models\SystemFlags;
use App\Models\Products;
use App\Models\Person;
use App\Models\PriceList;
use App\Models\User;
use App\Models\userHasRoles;
use Spatie\Permission\Models\Role;

$userid = $_POST['user']??'';
$roleid = $_POST['role']??'';
?>
@extends('master')

@section('title')
Assign Roles
@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Assign Roles</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol style="display:none;" class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v3</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- /.col-md-6 -->
          <div class="col-lg-12">
              <div class="card">
                 <div class="card-body">
                    <form method="POST" action="{{route('role.assignRoleToUser')}}">  
                    @csrf
                    <div class="col-md-4">  
                     <div class="mb-3">
                       <label class="form-label">Users</label> <br>
                       <select class="form-control" id="userid" name="userid"
                       <?php echo ($userid != '' ? "readonly":""); ?>>
                        <option >Select User</option>
                        @foreach($users as $user)
                         <option value="{{$user->id}}" <?php echo ($userid == $user->id? "selected":""); ?>>{{$user->name}}</option>
                        @endforeach
                      </select>                   
                      </div>       
                      <div class="mb-3">
                       <label class="form-label">Roles</label> <br>
                       <select class="form-control" id="rolename" name="rolename">
                         <option>Select Role</option>
                         @foreach($roles as $role)
                          <option value="{{$role->name}}" <?php echo ($roleid == $role->id? "selected":""); ?>>{{$role->name}}</option>
                         @endforeach
                       </select>                     
                      </div> 
                      <div class="mb-3">
                           <input type="submit" class="btn btn-primary" value="Assign Role" />
                      </div>  
                </div>
                </form>
              </div>  
            </div>

            <div class="card">                              
              <div class="card-body table-responsive p-0">
                  <table id="productsDataTable" class="table table-hover table-bordered table-striped">
                      <thead>
                          <tr>
                              <th>Name</th>
                              <th>Role</th>
                              <th>Action</th>
                          </tr>
                      </thead>
                      <tbody>
                          @forelse (userHasRoles::all() as $user)
                              <tr>
                                  <td>{{ $user->UserName->name }}</td>
                                  <td>{{ $user->RoleName->name }}</td>
                                  <td>
                                      <a onclick="fillUserAndRole({{$user->role_id.','.$user->model_id}});" class="btn btn-sm btn-warning">Edit</a>
                                  </td>
                              </tr>
                          @empty
                              <tr>No Result Found</tr>
                          @endforelse
                      </tbody>
                  </table>
              </div>
            <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.row -->
       
        <!-- /.card-body -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  @endsection()

@section('scripts')
<script>

function fillUserAndRole(roleId,userId){
  var roleId = roleId;//$('#rolename').val();
  var userId = userId;//$('#userid').val();
  var form = $('<form action="/assignRoleToUser" method="post">@csrf' +
  '<input type="text" name="role" value="' + roleId + '" />' +
  '<input type="text" name="user" value="' + userId + '" />' +
  '</form>');
  $('body').append(form);
  form.submit();
  // window.location.href = "/assignRoleToUser?role="+roleId+"&user="+userId;
}

  $(function () {
    // $('#invoice_date').val(new Date().toDateInputValue());
    $('#invoiceDataTable').DataTable({
      "initComplete": function () {
            // Apply the search
            this.api().columns().every( function () {
                var that = this;
 
                $( 'input', this.footer() ).on( 'keyup change clear', function () {
                    if ( that.search() !== this.value ) {
                        that
                            .search( this.value )
                            .draw();
                    }
                } );
            } );
        },
      "dom": 'Bfrtip',
      "buttons": [
            'copyHtml5',
            'excelHtml5',
            'csvHtml5',
            'pdfHtml5',
            'colvis'
        ],
      "paging": true,
      "lengthChange": false,
      "searching": true,
      "ordering": true,
      "info": true,
    });
  });

</script>
@endsection()

resources/views/role/index.blade.php
@extends('master')

@section('title')
Roles
@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Roles</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol style="display:none;" class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v3</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- /.col-md-6 -->
          <div class="col-lg-12">
            <div class="card">  
            @if(isset($roleData) )
            <form method="POST" action="{{ route('role.store') }}">
                @csrf
                <div class="card-body">
                      <div class="form-group">
                        <label for="name">Role Id</label>
                        <input type="text" name="id"  id="id" class="form-control @error('id') is-invalid @enderror" value="{{ $roleData->id }}" readonly>
                        @error('id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="name">Role Name</label>
                        <input type="text" name="name"  id="name" class="form-control @error('name') is-invalid @enderror" 
                                value="{{ $roleData->name }}" required placeholder="Role Name" autocomplete="off">
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Update Roles</button>
                </div>
              </form>
            @else
            <form method="POST" action="{{ route('role.store') }}">
                @csrf
                <div class="card-body">
                      <div class="form-group">
                        <label for="name">Role Id</label>
                        <input type="text" name="id"  id="id" class="form-control @error('id') is-invalid @enderror" value="{{ old('id') }}" readonly>
                        @error('id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="name">Role Name</label>
                        <input type="text" name="name"  id="name" class="form-control @error('name') is-invalid @enderror" 
                              value="{{ old('name') }}" required placeholder="Role Name" autocomplete="off">
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Create Roles</button>
                </div>
              </form>
            @endif
              
            </div>
            <div class="card">                              
              <div class="card-body table-responsive p-0">
                  <table id="rolesDataTable" class="table table-hover table-bordered table-striped">
                      <thead>
                          <tr>
                              <th>ID</th>
                              <th>Roles</th>
                              <th>Date Posted</th>
                              <th>Action</th>
                          </tr>
                      </thead>
                      <tbody>
                          @forelse ($roles as $role)
                              <tr>
                                  <td>{{ $role->id }}</td>
                                  <td>{{ $role->name }}</td>
                                  <td>{{ $role->created_at }}</td>
                                  <td>
                                      <a href="{{ route('role.edit', $role->id) }}" class="btn btn-sm btn-warning">Edit Role</a>
                                      <a href="{{ route('role.assignpermission', ['id'=>$role->id]) }}" class="btn btn-sm btn-success">Permission</a>
                                     
                                    </td>
                              </tr>
                          @empty
                              <tr>No Result Found</tr>
                          @endforelse
                      </tbody>
                  </table>
              </div>
            <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  @endsection()

@section('scripts')
<script>
  $(function () {
    $('#rolesDataTable').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
@endsection()