routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

//Add Controller
Route::resource('user','UserController');
//Route::resource('permission','PermissionController');
Route::resource('role','RoleController');
Route::resource('products','ProductsController');
Route::resource('systemFlags','SystemFlagsController');
Route::resource('select2Search','Select2SearchController');
Route::resource('person','PersonController');
Route::resource('invoice','InvoiceController');
Route::resource('priceList','PriceListController');
Route::resource('accounts','AccountsController');

Route::get('/accountHead', 'AccountsController@accountHead')->middleware(['auth'])->name('accounts.accountHead');
Route::get('/PriceList', 'PriceListController@PriceList')->middleware(['auth'])->name('priceList.PriceList');
Route::get('/priceList/productRateUpdate/{id}/{price}', 'PriceListController@ProductRateUpdate')->middleware(['auth']);
Route::get('/salesInvoice', 'InvoiceController@salesInvoice')->middleware(['auth'])->name('invoice.salesInvoice');
Route::get('/SIASO', 'InvoiceController@SIASO')->middleware(['auth'])->name('invoice.SIASO');
Route::get('/salesOrder', 'InvoiceController@salesOrder')->middleware(['auth'])->name('invoice.salesOrder');
Route::get('/printSalesInvoice/{id}', 'InvoiceController@printSalesInvoice')->middleware(['auth'])->name('invoice.printSalesInvoice');

Route::get('/purchaseInvoice', 'InvoiceController@purchaseInvoice')->middleware(['auth'])->name('invoice.purchaseInvoice');
Route::get('/purchaseOrder', 'InvoiceController@purchaseOrder')->middleware(['auth'])->name('invoice.purchaseOrder');
Route::get('/PIAPO', 'InvoiceController@PIAPO')->middleware(['auth'])->name('invoice.PIAPO');

Route::get('/customers', 'PersonController@customers')->middleware(['auth'])->name('person.customers');
Route::get('/supplier', 'PersonController@supplier')->middleware(['auth'])->name('person.supplier');

Route::get('/products', 'ProductsController@products')->middleware(['auth'])->name('products.products');
Route::post('/storeProducts', 'ProductsController@storeProducts')->middleware(['auth'])->name('products.storeProducts');

Route::get('/unit', 'SystemFlagsController@unit')->middleware(['auth'])->name('systemFlags.unit');
Route::post('/storeUnit', 'SystemFlagsController@storeUnit')->middleware(['auth'])->name('systemFlags.storeUnit');

Route::get('/category', 'SystemFlagsController@category')->middleware(['auth'])->name('systemFlags.category');
Route::post('/storeCategory', 'SystemFlagsController@storeCategory')->middleware(['auth'])->name('systemFlags.storeCategory');

Route::get('/search', 'Select2SearchController@search')->middleware(['auth'])->name('select2Search.index');
Route::get('/ajax-autocomplete-search', 'Select2SearchController@selectSearch')->middleware(['auth'])->name('select2Search.selectSearch');

Route::get('/profile', 'UserController@profile')->middleware(['auth'])->name('user.profile');


Route::post('/profile', 'UserController@postProfile')->middleware(['auth'])->name('user.postProfile');
Route::post('/addprofile', 'UserController@addProfile')->middleware(['auth'])->name('user.addProfile');
Route::get('/registration', 'UserController@userRegistration')->middleware(['auth'])->name('user.userRegistration');


Route::post('/assignRoleToUser', 'RoleController@assignRoleToUser')->middleware(['auth'])->name('role.assignRoleToUser');
Route::get('/assignroles', 'RoleController@assignroles')->middleware(['auth'])->name('role.assignroles');
Route::post('/addassignroles', 'RoleController@addassignroles')->middleware(['auth'])->name('role.addassignroles');
Route::get('/assignpermission', 'RoleController@assignpermission')->middleware(['auth'])->name('role.assignpermission');
Route::post('/addpermission', 'RoleController@addpermission')->middleware(['auth'])->name('role.addpermission');
Route::get('/createpermission', 'RoleController@createpermission')->middleware(['auth'])->name('role.createpermission');
Route::post('/assignpermissiontorole', 'RoleController@assignpermissiontorole')->middleware(['auth'])->name('role.assignpermissiontorole');
Route::get('/unassignpermissiontorole/{roleid}/{permissionid}', 'RoleController@unassignpermissiontorole')->middleware(['auth'])->name('role.unassignpermissiontorole');

// Route::post('/password/change', 'UserController@postPassword')->middleware(['auth'])->name('userPostPassword');



require __DIR__.'/auth.php';

app/Models/Products.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Products extends Model
{
    use HasFactory;

    
    protected $primaryKey = 'id';
    protected $fillable = ['name','parentProductId','salesPrice','purchasePrice',
                            'categoryId','unitId','productType'];



    public function UnitName(){
        return $this->belongsTo('App\Models\SystemFlags', 'unitId');
    }

    public function CategoryName(){
        return $this->belongsTo('App\Models\SystemFlags', 'categoryId');
    }

    public function ParentProductName(){
        return $this->belongsTo('App\Models\products', 'parentProductId');
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Products;
use Config;

class ProductsController extends Controller
{

    public function __construct(products $products)
    {
        $this->middleware("auth");
    }

    public function show($id)
    {
        $Data = Products::find($id);
        
        $productType = $Data->productType;

        Products::where('id', $id)->delete();
        $model = new Products();
        $model->productType = $productType;
        return redirect()->route('products.products',['model'=>$model])->with('success',$Data->name.'  deleted');
        
    }    
    

    public function destroy($id)
    {
        //it goes to show method
    }

    public function store(Request $request)
    {
        $validateData = $request->validate([
            'name' => 'required|string',
            'parentProductId' => 'nullable',
            'salesPrice' => 'nullable',
            'purchasePrice' => 'nullable',
            'productType' => 'string',
            'unitId' => 'required|integer',
            'categoryId' => 'required|integer'
            
        ]);

        
        if(!empty($request->id)){
            $products = Products::find($request->id);
            $products->fill($validateData);
            $products->updated_at = date("Y-m-d h:i:s");
            $products->modifiedBy = auth()->user()->name;
            if($products->save()){
                $model = new Products();
                $model->productType = $products->productType;        
                return redirect()->route('products.products', ['model'=>$model])->with('success', $request["name"].' Updated');
            }else{
                return redirect()->route('products.products', ['model'=>$products])->with('error', 'Error Occured');
            }

        }else{
            $products = new Products();
            
            $products->fill($validateData);
            $products->created_at = date("Y-m-d h:i:s");
            $products->createdBy = auth()->user()->name;
            
            if($products->save()){
                $model = new Products();
                $model->productType = $products->productType;        
                return redirect()->route('products.products', ['model'=>$model])->with('success', $request["name"].' Created');
            }else{
                return redirect()->route('products.products', ['model'=>$products])->with('error', 'Error Occured');
            }
        }
        
        
    }

    public function edit($id)
    {
        $model = Products::find($id);
        return view('products.products', ['model'=>$model]);
        
    }

    public function products()
    {
        $model = new Products();
        $model->productType = Config::get('constants.constants.finishProduct');
        return view('products.products', ['model'=>$model]);
    }

}

resources/views/products/products.blade.php
<?php 
use App\Models\SystemFlags;
use App\Models\Products;
?>
@extends('master')

@section('title')
Products
@endsection

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Products</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol style="display:none;" class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v3</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- /.col-md-6 -->
          <div class="col-lg-12">
            <div class="col-lg-12">
              <div class="card"> 
                <div class="card-header">
                  <h3 class="card-title">Add</h3>
      
                  <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-remove"></i></button>
                  </div>
                </div>
                 {{--Card header End  --}}
                <form method="POST" action="{{ route('products.store') }}">
                  @csrf
                  <div class="card-body">
                    <div style = 'display:none' class="row">
                          <div class="col-md-6">
                            <div class="form-group">
                              <label for="id">Product Type</label>
                              <input type="text" name="productType"  id="productType" class="form-control @error('productType') is-invalid @enderror" value="{{  $model->productType }}" readonly>
                              @error('productType')
                                  <span class="invalid-feedback" role="alert">
                                      <strong>{{ $message }}</strong>
                                  </span>
                              @enderror
      
                              
                            </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-md-6">
                            <div class="form-group">
                              <label for="id">Id</label>
                              <input type="text" name="id"  id="id" class="form-control @error('id') is-invalid @enderror" value="{{  $model->id }}" readonly>
                              @error('id')
                                  <span class="invalid-feedback" role="alert">
                                      <strong>{{ $message }}</strong>
                                  </span>
                              @enderror
      
                              
                            </div>
                            <!-- /.form-group -->
                            <div class="form-group">
                              <label for="categoryId">Categoery</label><br>
                            <select type="text" name="categoryId"  id="categoryId" class="form-control select2bs4 @error('categoryId') is-invalid @enderror" 
                                placeholder="Select Category" autocomplete="off">
                                <option value="" >Select Category</option>
                                @foreach (SystemFlags::where('flagType','CATEGORY')->get() as $Category)
                                  <option {{ $model->categoryId == $Category->id ? "selected" : "" }} value="{{ $Category->id }}">{{ $Category->flagName }}</optiarton>                                  
                            @endforeach
                        </select>
                        @error('categoryId')
                                  <span class="invalid-feedback" role="alert">
                                      <strong>{{ $message }}</strong>
                                  </span>
                              @enderror

                            </div>
                            <!-- /.form-group -->
                            
                            <div class="form-group">
                              <label for="salesPrice">Sales Price</label>
                              <input type="number" name="salesPrice"  id="salesPrice" class="form-control @error('salesPrice') is-invalid @enderror" value="{{ $model->salesPrice }}">
                              @error('salesPrice')
                                  <span class="invalid-feedback" role="alert">
                                      <strong>{{ $message }}</strong>
                                  </span>
                              @enderror

                            </div>
                            <!-- /.form-group -->
                            
                            <div class="form-group">
                              <label for="parentProductId">Parent Product</label><br>
                            <select type="text" name="parentProductId"  id="parentProductId" class="form-control select2bs4 @error('parentProductId') is-invalid @enderror" 
                                    placeholder="Select Parent Product (Optional)" autocomplete="off">
                                    <option value='' >Select Parent Product (Optional)</option>
                                    @foreach (Products::where('productType',$model->productType)->where("id",'<>',$model->id)->get() as $products)
                                      <option {{ ($model->parentProductId == $products->id) ? "selected" : "" }} value="{{ $products->id }}">{{ $products->name }}</option>                                  
                                @endforeach
                            </select>
                            @error('parentProductId')
                                  <span class="invalid-feedback" role="alert">
                                      <strong>{{ $message }}</strong>
                                  </span>
                              @enderror
                            </div>
                            <!-- /.form-group -->
                            
                          </div>
                          <div class="col-md-6">
                            
                            <div class="form-group">
                              
                              <label for="name">Name</label>
                              <input type="text" name="name"  id="name" class="form-control @error('name') is-invalid @enderror" value="{{ $model->name }}">
                              @error('id')
                                  <span class="invalid-feedback" role="alert">
                                      <strong>{{ $message }}</strong>
                                  </span>
                              @enderror
                          </div>
                          <!-- /.form-group -->
                            <div class="form-group">
                              <label for="unitId">Unit</label>
                            <br>
                            <select type="text" name="unitId"  id="unitId" class="form-control select2bs4 @error('unitId') is-invalid @enderror" 
                                placeholder="Select Unit" autocomplete="off">
                                <option value="" >Select Unit</option>
                                @foreach (SystemFlags::where('flagType','UNIT')->get() as $Unit)
                                  <option {{ ($model->unitId == $Unit->id) ? "selected" : "" }} value="{{ $Unit->id }}">{{ $Unit->flagName }}</option>                                  
                            @endforeach
                        </select>
                        @error('unitId')
                                  <span class="invalid-feedback" role="alert">
                                      <strong>{{ $message }}</strong>
                                  </span>
                              @enderror

                            </div>
                            <!-- /.form-group -->

                            <div class="form-group">
                              <label for="purchasePrice">Purchase Price</label>
                              <input type="number" name="purchasePrice"  id="purchasePrice" class="form-control @error('purchasePrice') is-invalid @enderror" value="{{ $model->purchasePrice }}">
                              @error('purchasePrice')
                                  <span class="invalid-feedback" role="alert">
                                      <strong>{{ $message }}</strong>
                                  </span>
                              @enderror
                            </div>
                            <!-- /.form-group -->

                          </div>
                        </div>
                  </div>
                  <div class="card-footer">
                  @if(userHasPermission('Add Product'))
                      <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> {{$model->id == '' ? ' Create' : " Update"}}</button>
                  @endif
                  </div>
                </form>  
              </div>  
            </div>
            <div class="card">                              
              <div class="card-body table-responsive p-0">
                  <table id="productsDataTable" class="table table-hover table-bordered table-striped">
                      <thead>
                          <tr>
                              <th>ID</th>
                              <th>Name</th>
                              <th>ParentName</th>
                              <th>Type</th>
                              <th>Category</th>
                              <th>Unit</th>
                              <th>Saleing Price</th>
                              <th>Action</th>
                          </tr>
                      </thead>
                      <tbody>
                          @forelse (Products::all() as $product)
                              <tr>
                                  <td>{{ $product->id }}</td>
                                  <td>{{ $product->name }}</td>
                                  <td>{{ $product->parentProductName->name??'' }}</td>
                                  <td>{{ $product->productType }}</td>
                                  <td>{{ $product->CategoryName->flagName??'' }}</td><!--<td>{{ SystemFlags::getSystemFlagName($product->categoryId) }}</td>-->
                                  <td>{{ $product->UnitName->flagName??'' }}</td><!--<td>{{ SystemFlags::getSystemFlagName($product->unitId) }}</td>-->
                                  <td>{{ $product->salesPrice }}</td>
                                  <td>
                                     @if(userHasPermission('Edit Product'))
                                      <a href="{{ route('products.edit', $product->id) }}" class="btn btn-sm btn-warning">Edit</a>
                                     @endif
                                     @if(userHasPermission('Delete Product'))
                                      <a href="{{ route('products.destroy', $product->id) }}" class="btn btn-sm btn-danger">Delete</a>
                                     @endif
                                    </td>
                              </tr>
                          @empty
                              <tr>No Result Found</tr>
                          @endforelse
                      </tbody>
                  </table>
              </div>
            <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  @endsection()

@section('scripts')
<script>
  $('#parentProductId').select2();
  $('#categoryId').select2();
  $('#unitId').select2();
  $(function () {
    $('#productsDataTable').DataTable({
      "initComplete": function () {
            // Apply the search
            this.api().columns().every( function () {
                var that = this;
 
                $( 'input', this.footer() ).on( 'keyup change clear', function () {
                    if ( that.search() !== this.value ) {
                        that
                            .search( this.value )
                            .draw();
                    }
                } );
            } );
        },
      "dom": 'Bfrtip',
      "buttons": [
            'copyHtml5',
            'excelHtml5',
            'csvHtml5',
            'pdfHtml5',
            'colvis'
        ],
      "paging": true,
      "lengthChange": false,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });

  // $("#salesPrice").change(function(){
  //   debugger;
  //   var salesPrice = parseInt($("#salesPrice").val());
  //   var purchasePrice = parseInt($("#purchasePrice").val());
  //   if ( !isNaN(purchasePrice) && purchasePrice != 0 && salesPrice < purchasePrice  ){
  //     $("salesPrice").css("border", "red");
  //   }else{
  //     $("salesPrice").css("background-color", "white");
  //   }
  // });
</script>
@endsection()